CFLAGS: -std=c++20 -Wall -Wextra -pedantic

correct:
	g++ -std=c++20 -Wall -Wextra -pedantic correct.cpp -o correct.out

aboba:
	g++ -std=c++20 -Wall -Wextra -pedantic aboba.cpp -o aboba.out

1977LC:
	g++ -std=c++20 -Wall -Wextra -pedantic 1977LC.cpp -o 1977LC.out

main:
	g++ -std=c++20 -Wall -Wextra -pedantic main.cpp -o main.out
	./main.out

prob:
	g++ -std=c++20 -Wall -Wextra -pedantic prob.cpp -o prob.out
	./prob.out

tmp:
	g++ -std=c++20 -Wall -Wextra -pedantic tmp.cpp -o tmp.out
	./tmp.out

clear:
	rm *.out